[package]
name = "function_calls"
version = "0.0.0"

[addresses]
bench = "0x1"

[dependencies]
MoveStdlib = { local = "../../../aptos-move/framework/move-stdlib" }
AptosStdlib = { local = "../../../aptos-move/framework/aptos-stdlib" }
AptosFramework = { local = "../../../aptos-move/framework/aptos-framework" }
