{{- if .Values.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aptos-validator.validatorServiceAccountName" . }}
  labels:
    {{- include "aptos-validator.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aptos-validator.fullnodeServiceAccountName" . }}
  labels:
    {{- include "aptos-validator.labels" . | nindent 4 }}
--- 
{{- end -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aptos-validator.fullname" . }}-haproxy
  labels:
    {{- include "aptos-validator.labels" . | nindent 4 }}
